import datetime as dt

from model import Sentiment, Author, Reddit, Comment, SentimentAnalysis

test_author_from_raw_json_cases = [
    (
        {
            "type": "comment",
            "subreddit": "nextfuckinglevel",
            "body": "I am so fucking jealous.  Petting a moose is on my bucket list.",
            "author": "MooseWhisperer09",
            "author_flair_background_color": None,
            "author_flair_css_class": None,
            "author_flair_richtext": [],
            "author_flair_template_id": None,
            "author_flair_text": None,
            "author_flair_text_color": None,
            "author_flair_type": "text",
            "author_fullname": "t2_cqmfh",
            "author_is_blocked": False,
            "author_patreon_flair": False,
            "author_premium": False,
            "created": 1756836531.0,
            "created_utc": 1756836531.0,
            "url": "https://www.reddit.com/r/nextfuckinglevel/comments/1n6muyq/an_enormous_moose_approaches_the_camera_and_get/nc1yqtj/"
        },
        Author(
            name="MooseWhisperer09",
            background_color=None,
            css_class=None,
            richtext=None,
            template_id=None,
            text=None,
            text_color=None,
            type="text",
            fullname="t2_cqmfh",
            is_blocked=False,
            is_patreon_flair=False,
            is_premium=False,
            datetime_created=dt.datetime(2025, 9, 2, 20, 8, 51),
            datetime_created_utc=dt.datetime(2025, 9, 2, 20, 8, 51),
            permalink="/r/nextfuckinglevel/comments/1n6muyq/an_enormous_moose_approaches_the_camera_and_get/nc1yqtj/",
        )
    ), (
        {
            "type": "comment",
            "subreddit": "formuladank",
            "body": "slow button on",
            "author": "ch0c0l2te",
            "author_flair_background_color": "",
            "author_flair_css_class": "forsure",
            "author_flair_richtext": [
                {
                    "e": "text",
                    "t": "BWOAHHHHHHH "
                }
            ],
            "author_flair_template_id": None,
            "author_flair_text": "BWOAHHHHHHH ",
            "author_flair_text_color": "dark",
            "author_flair_type": "richtext",
            "author_fullname": "t2_h51w2",
            "author_is_blocked": False,
            "author_patreon_flair": False,
            "author_premium": True,
            "created": 1768657921.0,
            "created_utc": 1768657921.0,
            "url": "https://www.reddit.com/r/formuladank/comments/1qerdow/its_about_time/o03rw1q/"
        },
        Author(
            name="ch0c0l2te",
            background_color=None,
            css_class="forsure",
            richtext="[{\"e\": \"text\", \"t\": \"BWOAHHHHHHH \"}]",
            template_id=None,
            text="BWOAHHHHHHH ",
            text_color="dark",
            type="richtext",
            fullname="t2_h51w2",
            is_blocked=False,
            is_patreon_flair=False,
            is_premium=True,
            datetime_created=dt.datetime(2026, 1, 17, 14, 52, 1),
            datetime_created_utc=dt.datetime(2026, 1, 17, 14, 52, 1),
            permalink="/r/formuladank/comments/1qerdow/its_about_time/o03rw1q/",
        )
    )
]

test_reddit_from_raw_json_cases = [
    (
        {
            "id": "jgz2uz",
            "name": "t3_jgz2uz",
            "permalink": "/r/aww/comments/jgz2uz/we_live_in_a_basement_suite_so_i_built_a_loft_for/",
            "author": "CocaKoller",
            "title": "We live in a basement suite. So I built a loft for our corgi Wolfgang.",
            "body": "",
            "created": 1603498482.0,
            "created_utc": 1603498482.0,
            "likes": None,
            "ups": 115320,
            "downs": 0,
            "score": 115320,
            "upvote_ratio": 0.94,
            "gilded": 4,
            "subreddit_id": "t5_2qh1o",
            "subreddit_name": "aww",
            "num_comments": 820,
            "comments": []
        },
        "corgi",
        "2026-01-01",
        "2027-01-01",
        Reddit(
            reddit_id="jgz2uz",
            name="t3_jgz2uz",
            permalink="/r/aww/comments/jgz2uz/we_live_in_a_basement_suite_so_i_built_a_loft_for/",
            phrase="corgi",
            author="CocaKoller",
            title="We live in a basement suite. So I built a loft for our corgi Wolfgang.",
            body=None,
            datetime_created=dt.datetime(2020, 10, 24, 0, 14, 42),
            datetime_created_utc=dt.datetime(2020, 10, 24, 0, 14, 42),
            likes=None,
            ups=115320,
            downs=0,
            score=115320,
            upvote_ratio=0.94,
            gilded_number=4,
            number_of_comments=820,
            start_file_date="2026-01-01",
            end_file_date="2027-01-01"
        )
    ), (
        {
            "id": "135yzs1",
            "name": "t3_135yzs1",
            "permalink": "/r/BrandNewSentence/comments/135yzs1/corgisized_meteor_as_heavy_as_4_baby_elephants/",
            "author": "HELL-OAT",
            "title": "Corgi-sized meteor as heavy as 4 baby elephants",
            "body": "That's amazing!",
            "created": 1683058684.0,
            "created_utc": 1683058684.0,
            "likes": 37,
            "ups": 37097,
            "downs": 0,
            "score": 37097,
            "upvote_ratio": 0.96,
            "gilded": 0,
            "subreddit_id": "t5_mbn0j",
            "subreddit_name": "BrandNewSentence",
            "num_comments": 643,
            "comments": []
        },
        "corgi",
        "2022-01-01",
        "2023-01-01",
        Reddit(
            reddit_id="135yzs1",
            name="t3_135yzs1",
            permalink="/r/BrandNewSentence/comments/135yzs1/corgisized_meteor_as_heavy_as_4_baby_elephants/",
            phrase="corgi",
            author="HELL-OAT",
            title="Corgi-sized meteor as heavy as 4 baby elephants",
            body="That's amazing!",
            datetime_created=dt.datetime(2023, 5, 2, 20, 18, 4),
            datetime_created_utc=dt.datetime(2023, 5, 2, 20, 18, 4),
            likes=37,
            ups=37097,
            downs=0,
            score=37097,
            upvote_ratio=0.96,
            gilded_number=0,
            number_of_comments=643,
            start_file_date="2022-01-01",
            end_file_date="2023-01-01"
        )
    )
]

test_comment_from_raw_json_cases = [
    (
        {
            "id": "g9tw6ow",
            "parent_id": "t3_jgz2uz",
            "name": "t1_g9tw6ow",
            "permalink": "/r/aww/comments/jgz2uz/we_live_in_a_basement_suite_so_i_built_a_loft_for/g9tw6ow/",
            "author": "[deleted]",
            "body": "I like Wolfgang.",
            "created": 1603501599.0,
            "created_utc": 1603501599.0,
            "depth_level": 0,
            "controversiality": 0,
            "likes": None,
            "ups": 1013,
            "downs": 0,
            "score": 1013,
            "upvote_ratio": 1.0,
            "gilded": 0,
            "subreddit_id": "t5_2qh1o",
            "subreddit_name": "aww",
            "replies": [
                {"replies": []},
                {"replies": [
                    {"replies": []}, {"replies": []}, {"replies": []}
                ]},
                {"replies": [
                    {"replies": []}
                ]},
            ]
        },
        "g9tw6ow",
        "corgi",
        "2022-01-01",
        "2023-01-01",
        Comment(
            comment_id="g9tw6ow",
            reddit_id="g9tw6ow",
            parent_comment_id=None,
            name="t1_g9tw6ow",
            permalink="/r/aww/comments/jgz2uz/we_live_in_a_basement_suite_so_i_built_a_loft_for/g9tw6ow/",
            phrase="corgi",
            author=None,
            body="I like Wolfgang.",
            datetime_created=dt.datetime(2020, 10, 24, 3, 6, 39),
            datetime_created_utc=dt.datetime(2020, 10, 24, 3, 6, 39),
            depth_level=0,
            controversiality=False,
            likes=0,
            ups=1013,
            downs=0,
            score=1013,
            upvote_ratio=1.,
            gilded_number=0,
            number_of_replies=7,
            start_file_date="2022-01-01",
            end_file_date="2023-01-01"
        )
    ), (
        {
            "id": "g9v8jbi",
            "parent_id": "t1_g9u5mh6",
            "name": "t1_g9v8jbi",
            "permalink": "/r/aww/comments/jgz2uz/we_live_in_a_basement_suite_so_i_built_a_loft_for/g9v8jbi/",
            "author": "rognabologna",
            "body": "Please tell me he's named Wolfgang Puck, after the chef, but you call him Wolfgang Pup",
            "created": 1603522201.0,
            "created_utc": 1603522201.0,
            "depth_level": 2,
            "controversiality": 1,
            "likes": 18,
            "ups": 72,
            "downs": 0,
            "score": 72,
            "upvote_ratio": 1.0,
            "gilded": 3,
            "subreddit_id": "t5_2qh1o",
            "subreddit_name": "aww",
            "replies": []
        },
        "g9tw6ow",
        "corgi",
        "2026-01-01",
        "2027-01-01",
        Comment(
            comment_id="g9v8jbi",
            reddit_id="g9tw6ow",
            parent_comment_id="g9u5mh6",
            name="t1_g9v8jbi",
            permalink="/r/aww/comments/jgz2uz/we_live_in_a_basement_suite_so_i_built_a_loft_for/g9v8jbi/",
            phrase="corgi",
            author="rognabologna",
            body="Please tell me he's named Wolfgang Puck, after the chef, but you call him Wolfgang Pup",
            datetime_created=dt.datetime(2020, 10, 24, 8, 50, 1),
            datetime_created_utc=dt.datetime(2020, 10, 24, 8, 50, 1),
            depth_level=2,
            controversiality=True,
            likes=18,
            ups=72,
            downs=0,
            score=72,
            upvote_ratio=1.,
            gilded_number=3,
            number_of_replies=0,
            start_file_date="2026-01-01",
            end_file_date="2027-01-01"
        )
    )
]

test_sentiment_analysis_from_reddit_cases = [
    (
        Reddit(
            reddit_id="jgz2uz",
            name="t3_jgz2uz",
            permalink="/r/aww/comments/jgz2uz/we_live_in_a_basement_suite_so_i_built_a_loft_for/",
            phrase="corgi",
            author="CocaKoller",
            title="We live in a basement suite. So I built a loft for our corgi Wolfgang.",
            body=None,
            datetime_created=dt.datetime(2020, 10, 24, 0, 14, 42),
            datetime_created_utc=dt.datetime(2020, 10, 24, 0, 14, 42),
            likes=None,
            ups=115320,
            downs=0,
            score=115320,
            upvote_ratio=0.94,
            gilded_number=4,
            number_of_comments=820,
            start_file_date="2026-01-01",
            end_file_date="2027-01-01"
        ),
        "We live in a basement suite. So I built a loft for our cgi Wolfgang.",
        Sentiment(negative=0., neutral=1., positive=0., compound=0., polarity=0.13636363636363635, subjectivity=0.5),
        SentimentAnalysis(
            reddit_id="jgz2uz",
            comment_id="N/A",
            phrase="corgi",
            author="CocaKoller",
            text="We live in a basement suite. So I built a loft for our cgi Wolfgang.",
            datetime_created=dt.datetime(2020, 10, 24, 0, 14, 42),
            score=115320,
            upvote_ratio=0.94,
            gilded_number=4,
            number_of_comments=820,
            controversiality=False,
            s_neg=0.,
            s_neu=1.,
            s_pos=0.,
            s_com=0.,
            s_pol=0.13636363636363635,
            s_sub=0.5,
            file_date="2026-01-01"
        )
    ), (
        Reddit(
            reddit_id="135yzs1",
            name="t3_135yzs1",
            permalink="/r/BrandNewSentence/comments/135yzs1/corgisized_meteor_as_heavy_as_4_baby_elephants/",
            phrase="corgi",
            author="HELL-OAT",
            title="Corgi-sized meteor as heavy as 4 baby elephants",
            body="That's amazing!",
            datetime_created=dt.datetime(2023, 5, 2, 20, 18, 4),
            datetime_created_utc=dt.datetime(2023, 5, 2, 20, 18, 4),
            likes=37,
            ups=37097,
            downs=0,
            score=37097,
            upvote_ratio=0.96,
            gilded_number=0,
            number_of_comments=643,
            start_file_date="2022-01-01",
            end_file_date="2023-01-01"
        ),
        "Corgi-sized meteor as heavy as 4 baby elephants",
        Sentiment(negative=0., neutral=1., positive=0., compound=0., polarity=-0.2, subjectivity=0.5),
        SentimentAnalysis(
            reddit_id="135yzs1",
            comment_id="N/A",
            phrase="corgi",
            author="HELL-OAT",
            text="Corgi-sized meteor as heavy as 4 baby elephants",
            datetime_created=dt.datetime(2023, 5, 2, 20, 18, 4),
            score=37097,
            upvote_ratio=0.96,
            gilded_number=0,
            number_of_comments=643,
            controversiality=False,
            s_neg=0.,
            s_neu=1.,
            s_pos=0.,
            s_com=0.,
            s_pol=-0.2,
            s_sub=0.5,
            file_date="2022-01-01"
        )
    )
]

test_sentiment_analysis_from_comment_cases = [
    (
        Comment(
            comment_id="g9tw6ow",
            reddit_id="g9tw6ow",
            parent_comment_id=None,
            name="t1_g9tw6ow",
            permalink="/r/aww/comments/jgz2uz/we_live_in_a_basement_suite_so_i_built_a_loft_for/g9tw6ow/",
            phrase="corgi",
            author=None,
            body="I like Wolfgang.",
            datetime_created=dt.datetime(2020, 10, 24, 3, 6, 39),
            datetime_created_utc=dt.datetime(2020, 10, 24, 3, 6, 39),
            depth_level=0,
            controversiality=False,
            likes=0,
            ups=1013,
            downs=0,
            score=1013,
            upvote_ratio=1.,
            gilded_number=0,
            number_of_replies=7,
            start_file_date="2022-01-01",
            end_file_date="2023-01-01"
        ),
        "I like Wolfgang.",
        Sentiment(negative=0., neutral=0.286, positive=0.714, compound=0.3612, polarity=0., subjectivity=0.),
        SentimentAnalysis(
            reddit_id="N/A",
            comment_id="g9tw6ow",
            phrase="corgi",
            author=None,
            text="I like Wolfgang.",
            datetime_created=dt.datetime(2020, 10, 24, 3, 6, 39),
            score=1013,
            upvote_ratio=1.,
            gilded_number=0,
            number_of_comments=7,
            controversiality=False,
            s_neg=0.,
            s_neu=0.286,
            s_pos=0.714,
            s_com=0.3612,
            s_pol=0.,
            s_sub=0.,
            file_date="2022-01-01"
        )
    ), (
        Comment(
            comment_id="g9v8jbi",
            reddit_id="g9tw6ow",
            parent_comment_id="g9u5mh6",
            name="t1_g9v8jbi",
            permalink="/r/aww/comments/jgz2uz/we_live_in_a_basement_suite_so_i_built_a_loft_for/g9v8jbi/",
            phrase="corgi",
            author="rognabologna",
            body="Please tell me he's named Wolfgang Puck, after the chef, but you call him Wolfgang Pup",
            datetime_created=dt.datetime(2020, 10, 24, 8, 50, 1),
            datetime_created_utc=dt.datetime(2020, 10, 24, 8, 50, 1),
            depth_level=2,
            controversiality=True,
            likes=18,
            ups=72,
            downs=0,
            score=72,
            upvote_ratio=1.,
            gilded_number=3,
            number_of_replies=0,
            start_file_date="2026-01-01",
            end_file_date="2027-01-01"
        ),
        "Please tell me he's named Wolfgang Puck, after the chef, but you call him Wolfgang Pup",
        Sentiment(negative=0., neutral=0.901, positive=0.099, compound=0.1655, polarity=0., subjectivity=0.),
        SentimentAnalysis(
            reddit_id="N/A",
            comment_id="g9v8jbi",
            phrase="corgi",
            author="rognabologna",
            text="Please tell me he's named Wolfgang Puck, after the chef, but you call him Wolfgang Pup",
            datetime_created=dt.datetime(2020, 10, 24, 8, 50, 1),
            score=72,
            upvote_ratio=1.,
            gilded_number=3,
            number_of_comments=0,
            controversiality=True,
            s_neg=0.,
            s_neu=0.901,
            s_pos=0.099,
            s_com=0.1655,
            s_pol=0.,
            s_sub=0.,
            file_date="2026-01-01"
        )
    )
]
