# File objects providers
from provider.file.i_file_object_provider import IFileObjectProvider

# JSON objects providers
from provider.json_file.i_json_file_object_provider import IJsonFileObjectProvider
from provider.json_file.json_file_object_provider import JsonFileObjectProvider

# JSON entities providers
from provider.json_file.i_json_reddit_provider import IJsonRedditProvider
from provider.json_file.i_json_comment_provider import IJsonCommentProvider
from provider.json_file.i_json_author_provider import IJsonAuthorProvider
from provider.json_file.json_reddit_provider import JsonRedditProvider
from provider.json_file.json_comment_provider import JsonCommentProvider
from provider.json_file.json_author_provider import JsonAuthorProvider

# Supabase database providers
from provider.db.i_db_provider import IDbProvider
from provider.supabase_postgres.supabase_postgres_provider import SupabasePostgresProvider

# Supabase entities providers
from provider.db.i_db_reddit_provider import IDbRedditProvider
from provider.db.i_db_comment_provider import IDbCommentProvider
from provider.db.i_db_author_provider import IDbAuthorProvider
from provider.db.i_db_sentiment_analysis_provider import IDbSentimentAnalysisProvider
from provider.supabase_postgres.supabase_postgres_reddit_provider import SupabasePostgresDbRedditProvider
from provider.supabase_postgres.supabase_postgres_comment_provider import SupabasePostgresDbCommentProvider
from provider.supabase_postgres.supabase_postgres_author_provider import SupabasePostgresDbAuthorProvider
from provider.supabase_postgres.supabase_postgres_sentiment_analysis_provider import SupabasePostgresDbSentimentAnalysisProvider
