from provider.i_db_provider import IDbProvider
from provider.supabase_postgres_provider import SupabasePostgresProvider

from provider.i_db_reddit_provider import IDbRedditProvider
from provider.i_db_comment_provider import IDbCommentProvider
from provider.i_db_author_provider import IDbAuthorProvider
from provider.i_db_sentiment_analysis_provider import IDbSentimentAnalysisProvider
from provider.supabase_postgres_reddit_provider import SupabasePostgresDbRedditProvider
from provider.supabase_postgres_comment_provider import SupabasePostgresDbCommentProvider
from provider.supabase_postgres_author_provider import SupabasePostgresDbAuthorProvider
from provider.supabase_postgres_sentiment_analysis_provider import SupabasePostgresDbSentimentAnalysisProvider

from provider.i_file_object_provider import IFileObjectProvider
from provider.i_json_file_object_provider import IJsonFileObjectProvider
from provider.json_file_object_provider import JsonFileObjectProvider

from provider.i_file_reddit_provider import IFileRedditProvider
from provider.i_file_comment_provider import IFileCommentProvider
from provider.i_file_author_provider import IFileAuthorProvider
from provider.json_reddit_provider import JsonRedditProvider
from provider.json_comment_provider import JsonCommentProvider
from provider.json_author_provider import JsonAuthorProvider
